### ISSUE TITLE
zs2 File from testXpert III

### ISSUE THREAD

**Issue by 0xel** [cpetrich/zs2decode#10]
Hey. I got a bunch of testXpert III Data-files. It seems like Zwick altered something in their file format as the chucks-to-XML function quits stating 'something is wrong with the DD-segments count over the end-segments count'. I was able to alter your code to have an output of number DDs vs Ends. There are about 100 ends less than DDs.

Unfortunately I'm not that good as a programmer to understand what the issue is (beside the difference in numbers and (I assume) the resulting nesting of data that relates to some structure?).

Do you pan to update your code for zs2 files from testXpert III? Should it be working and there is something wrong with the data files? Do you have any clue where to start in my situation?

Best

**Comment by cpetrich** [comment]
Hi 0xel,

1. I've never gotten my hands on a testXpert III file, so I have no reason to believe the code should work. Hence, I would assume your data files are fine.
2. I would definitely look into the testXpert III file format once I get my hands on such files. I have less time available for this now than I used to but I would certainly have a look.
3. In your situation, the first thing I would do is change `f.write( zs2decode.util.chunks_to_XML(chunks) )` to `f.write( zs2decode.util.chunks_to_text_dump(chunks) )` to see if that gives meaningful output. Maybe that plus some time browsing the dump file is all that's required to find what you are after.

Let me know if you have textXpert III files to share.

**Comment by 0xel** [comment]
Hey,

Thanks for your reply.

What makes me think your code may work is that just the "export" to xml is not working. I assume you implemented test for correct "syntax" of the data set? So there is "just" an issue with the correct output?

What do you need? I will create those files. An empty file containing no data, A file containing one and multiple datasets?

I already made those changes you suggested and I got some output. To me it does not make any sense. How can I share those files with you? Is there any feature on GitHub allowing for private communication?

**Comment by cpetrich** [comment]
I'd need at least one file with one or more datasets, generated by testXpert III. You can send me a download link to _removed@email.com_.

**Comment by 0xel** [comment]
shot you an e-mail. should arrive soon.
If there is anything I can do, please let me know.

**Comment by cpetrich** [comment]
Thank you.

Chunks of type ``0x00`` were added which work exactly like ``0xAA`` but are used to encode not only strings but also numerical values as strings. Looks like these chunks are used where capabilities were added to testXpert III.

Updated code is in the repository.

**Comment by 0xel** [comment]
works like a charm. Thank you!
