### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by Drellon** [cpetrich/zs2decode#6]
Hello, 
everytime I get the following error message when I´m trying to raw data dump my XML: 

> Reading XML
> Parsing XML
> Findig data
> 1
> Traceback (most recent call last):
>   File "raw_data_dump_from_xml.py", line 142, in <module>
>     channels.remove(data[sample_name]['time_channel_ID'])
> ValueError: list.remove(x): x not in list

I´m using Python 2.7. btw great work man!

**Comment by cpetrich** [comment]
Thanks.

Tried to implement a work-around. Does that work for you?

**Comment by Drellon** [comment]
Thanks for your fast respon. I can try this only in 3 days. I'll let you know.

Greets

**Comment by Drellon** [comment]
Hello, now I get this error: 

> Reading XML
> Parsing XML
> Findig data
> 1
> Traceback (most recent call last):
>   File "raw_data_dump_from_xml.py", line 151, in <module>
>     line = '\t'.join(['"'+str(channel_names[channel])+'"' for channel in channe
> s])
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 27
>  ordinal not in range(128)

**Comment by cpetrich** [comment]
this may take some fiddling to get to work in both 2.7 and 3+: can you can
share the XML or zs2 file?

**Comment by Drellon** [comment]
No, unfortunately im not allowed to share this file. :(

**Comment by cpetrich** [comment]
I made a guess. Does the current version work for you?

**Comment by Drellon** [comment]
I´ve tried now with Python 3.6. Now it works fine, thank you!
